default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tony_app_development
  username: wendi

test:
  <<: *default
  database: tony_app_test
  username: wendi
